server {
    listen       80;
    server_name  _;
    root         /usr/share/nginx/html;

    # Real WPAD clients expect this MIME type.
    default_type application/x-ns-proxy-autoconfig;

    location /wpad.dat {
        # Disable caching so iterating on the script during dev is painless.
        add_header Cache-Control "no-store" always;
    }
}
